### ISSUE TITLE
[LazyModel] nullpointer when setting nested models

### ISSUE THREAD

**Issue by tahitiangabriel** [wicketstuff/core#599]
@svenmeier 
Hello Sven,

When I use LazyModel with nested models if one of the nested model is null, the setter returns a NullPointerException : 
java.lang.NullPointerException: null
        at org.wicketstuff.lazymodel.LazyModel.setObject(LazyModel.java:276)
        at org.wicketstuff.lazymodel.LazyModelTest.setObject(LazyModelTest.java:286)

If I use a PropertyModel instead, it works just fine as it instantiate the nested objects as needed.

Here's the test I've modified to reproduce the problem (I added a setD setter in class B).

```Java
	@Test
	public void getNestedObject() {
		A a = new A();

		LazyModel<B> model = model(from(a).getB());

		assertEquals(B.class, model.getObjectClass());
		assertEquals("b", model.getPath());

		assertEquals(null, model.getObject());
	}

	@Test
	public void setNestedObject() {
		A a = new A();

		LazyModel<D> model = model(from(a).getB().getD());

		assertEquals(D.class, model.getObjectClass());
		assertEquals("b.d", model.getPath());

		D d = new D();
		model.setObject(d);

		assertEquals(d, a.b.d);
	}
```

**Comment by svenmeier** [comment]
PropertyResolver uses IGetAndSet#newValue() to create missing intermediate objects.

IMO this is a rather obscure feature, which fails in several cases (e.g. generic return, maps). I'd rather not duplicate this feature into LazyModel. Since LazyModel calls methods anyway, you can make them taking care of not returning any nulls.
