### ISSUE TITLE
Select2 statlesss throws error while adding default options

### ISSUE THREAD

**Issue by florianlacreuse** [wicketstuff/core#655]
Hi,

I just noticed that a stateless Select2 (using resource reference) with some default values (model not empty) will throws an exception during the `onComponentTagBody` since it tries to add select options for these values using the `provider` (`null` in this case).

https://github.com/wicketstuff/core/blob/a3f0e71a965c5b98ad90edeb96a8be7b806735c8/select2-parent/select2/src/main/java/org/wicketstuff/select2/AbstractSelect2Choice.java#L399-L404

To reproduce the issue, just add `new PropertyModel<Collection<Country>>(this, "countries")` as parameter here:

https://github.com/wicketstuff/core/blob/a3f0e71a965c5b98ad90edeb96a8be7b806735c8/select2-parent/select2-examples/src/main/java/org/wicketstuff/select2/HomePage.java#L192

```text
java.lang.IllegalStateException: Select2 choice component: statelessCountries does not have a ChoiceProvider set
     at org.wicketstuff.select2.AbstractSelect2Choice.getProvider(AbstractSelect2Choice.java:140)
     at org.wicketstuff.select2.AbstractSelect2Choice.addOption(AbstractSelect2Choice.java:402)
     at org.wicketstuff.select2.AbstractSelect2Choice.onComponentTagBody(AbstractSelect2Choice.java:442)
     at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2486)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1593)
     at org.apache.wicket.Component.internalRender(Component.java:2291)
     at org.apache.wicket.Component.render(Component.java:2222)
```

**Comment by martin-g** [comment]
The same is true also for stateful components. The application developer must provide a `ChoiceProvider` if a model is going to be used.

I will add an improvement to ignore the model when the component is stateless. This way the application can switch from stateless to stateful mode depending on external conditions.

**Comment by florianlacreuse** [comment]
If a stateful select2 component doesn't have a `ChoiceProvider`, I thinks it's the developer's fault.

For a stateless select2 component, since it use a `JsonResourceReference` which provide the `ChoiceProvider`, it's a bit odd to set the `provider` attribute (the one in `AbstractSelect2Choice`).

About your commit: from now on wicketstuff select2 connector will not create the pre selected values (https://select2.org/data-sources/ajax#default-pre-selected-values)? Having the value(s) from the model pre selected in the select seems very usefull.

WIth the actual source code, I'm able to avoid the error and have the pre selected values by setting the `provider` even if I use stateless mode with a resource reference. This "dummy" `ChoiceProvider` has an empty `query` method since it will not be used. This hack looks very dirty to me.

**Comment by lalmeras** [comment]
Am I missing something, or does the proposed patch prevents any pre-selection in select2 component (as writing <option...> is always skipped in stateless mode) ?

How is it expected to perform preselection in stateless mode with this patch ? Overriding onComponentTagBody to add option with custom dedicated code ?

**Comment by lalmeras** [comment]
@martin-g I think there is some misunderstanding on this issue, and on the way the fix you apply may forbid previously legit (from my point of view) usage of AbstractSelect2Choice.

First: **stateless** term was not used right. In Wicket, stateless is used for not persisted pages (so, stateless as no cross-request state). We (@lalmeras and @florianlacreuse) use it because it is the name of the attribute in org.wicketstuff.select2.Settings that allow to switch the source for select2 proposals:
* a component-based, ChoiceProvider implementation (stateless=false)
* a resource-based implementation (stateless=true)

On our side, we used to use AbstractSelect2Choice in a mixed configuration: stateful component (in a stateful page, ...), and a stateless Settings configured with a mounted ResourceReference.

We do it as it improves performance when the Select2Choice's page is really heavy, and so incurs some lag during page retrieval. Our stateless Settings allow to retrieve proposal without any page interaction.

The fix you apply breaks this use-case: our AbstractSelect2Choice is no longer populated with model-provided value.

Do you want to support this use-case (stateful wicket component, backed with proposals from a stateless ResourceReference) ? I think it is useful, either from a performance point-of-view, but also if we want to use this component with an external source for proposals.

**Comment by martin-g** [comment]
I didn't receive any notifications for the comments at March 22. Just now I see them because of the comment from today.

A Component could be stateless even without using a resource! There are several such components in wicket-core.

Please create new issue with a quickstart (and a PR if you know how to fix the issue yourself).
And please do not add a tone of unrelated information to it! It just makes it hard for us to understand the issue. A quickstart usually explains the issue the best. While doing it the reporters usually find a solution themselves or even find that there is not an issue.
