### ISSUE TITLE
annotationeventdispatcher and disabled components

### ISSUE THREAD

**Issue by svenmeier** [wicketstuff/core#680]
With https://github.com/wicketstuff/core/commit/f2ee61fb48259f9bdbf682713b12738e596d3cc1
AnnotationEventDispatcher uses #canCallListener() to prevent dispatches to invisible components. 

But since WICKET-6137 that method no longer has a method argument, so it is not possible for overrides to identify the initiator of the call, e.g. to allow event dispatching on an invisible component.
Overriding that method is dangerous anyway, since people might allow browser requests on disabled/invisible components. Furthermore it is tedious to override that method.

We should reintroduce AnnotationEventDispatcherConfig#dispatchToNonVisibleComponents.

**Comment by ams-tschoening** [comment]
The readme for the config of the dispatcher is still wrong:

https://github.com/wicketstuff/core/commit/d1b2ba0fa22476b4db55f2b646382dd5530480a4

Might be a better idea to remove implementation details like if `canCallListenerInterface` is called or not and about the individual available configs entirely instead of reverting to some older status. I suggest only keeping the following sentence of that section:

> The configuration object for the library, AnnotationEventDispatcherConfig, can be accessed via an application's metadata: Application.get().getMetaData(Initializer.ANNOTATION_EVENT_DISPATCHER_CONFIG_CONTEXT_KEY).
