### ISSUE TITLE
Error during startup when using a non-default theme

### ISSUE THREAD

**Issue by mcr-paulanand** [wicketstuff/core#933]

**Comment by reckart** [comment]
@solomax There was this PR to use Webjars for the JQuery UI themes - it looks like, we don't use webjars though and you have added a script to update the themes. Did using the webjars not work?

**Comment by solomax** [comment]
Hello @reckart, 

from what I can see in these commits/PRs (to be fair I totally forgot about these changes I've made ~2 years ago :)))

This is not about loading JQuery themes via WebJars, but about fixing theme switching
Due to JQueryUI itself is now being loaded via WebJars theme initializers need to be updated :))

**Comment by reckart** [comment]
Ah, ok. I got sidetracked by the title "[Use Webjars for JQuery UI themes](https://github.com/mcr-paulanand/core/commit/33662b571489a0ccfa9f8fb14eb18a9ee2b67410)" on the commit. Thanks for clarifying.
